/**
 * Oveda API
 * This API provides endpoints to interact with the Oveda data.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { EventCategoryDump } from './eventCategoryDump';
import { EventDump } from './eventDump';
import { EventReferenceDump } from './eventReferenceDump';
import { ImageDump } from './imageDump';
import { LocationDump } from './locationDump';
import { OrganizationDump } from './organizationDump';
import { OrganizerDump } from './organizerDump';
import { PlaceDump } from './placeDump';


export interface DumpResponse { 
    event_categories?: Array<EventCategoryDump>;
    event_references?: Array<EventReferenceDump>;
    events?: Array<EventDump>;
    images?: Array<ImageDump>;
    locations?: Array<LocationDump>;
    organizations?: Array<OrganizationDump>;
    organizers?: Array<OrganizerDump>;
    places?: Array<PlaceDump>;
}