/**
 * Oveda API
 * This API provides endpoints to interact with the Oveda data.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { EventCategoryRef } from './eventCategoryRef';
import { Image } from './image';
import { OrganizationRef } from './organizationRef';
import { OrganizerRef } from './organizerRef';
import { PlaceSearchItem } from './placeSearchItem';


export interface EventSearchItem { 
    booked_up?: boolean;
    categories?: Array<EventCategoryRef>;
    description?: string;
    end?: Date;
    readonly id?: number;
    name: string;
    organization?: OrganizationRef;
    organizer?: OrganizerRef;
    photo?: Image;
    place?: PlaceSearchItem;
    recurrence_rule?: string;
    start: Date;
    status?: EventSearchItem.StatusEnum;
}
export namespace EventSearchItem {
    export type StatusEnum = 'scheduled' | 'cancelled' | 'movedOnline' | 'postponed' | 'rescheduled';
    export const StatusEnum = {
        Scheduled: 'scheduled' as StatusEnum,
        Cancelled: 'cancelled' as StatusEnum,
        MovedOnline: 'movedOnline' as StatusEnum,
        Postponed: 'postponed' as StatusEnum,
        Rescheduled: 'rescheduled' as StatusEnum
    };
}