/**
 * Oveda API
 * This API provides endpoints to interact with the Oveda data.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Image { 
    copyright_text?: string;
    id?: number;
    /**
     * Append query arguments w for width, h for height or s for size(width and height).
     */
    image_url?: any;
}