/**
 * Oveda API
 * This API provides endpoints to interact with the Oveda data.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LocationPatchRequest { 
    city?: string;
    country?: string;
    /**
     * Latitude between (-90, 90)
     */
    latitude?: string;
    /**
     * Longitude between (-180, 180)
     */
    longitude?: string;
    postalCode?: string;
    state?: string;
    street?: string;
}