/**
 * Oveda API
 * This API provides endpoints to interact with the Oveda data.
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ErrorResponse } from '../model/errorResponse';
import { EventDate } from '../model/eventDate';
import { EventDateListResponse } from '../model/eventDateListResponse';
import { EventDateSearchResponse } from '../model/eventDateSearchResponse';
import { UnprocessableEntityResponse } from '../model/unprocessableEntityResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class EventDatesService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * List event dates
     *
     * @param page The page number (1 indexed).
     * @param perPage Items per page
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1EventDatesGet(page?: number, perPage?: number, observe?: 'body', reportProgress?: boolean): Observable<EventDateListResponse>;
    public apiV1EventDatesGet(page?: number, perPage?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EventDateListResponse>>;
    public apiV1EventDatesGet(page?: number, perPage?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EventDateListResponse>>;
    public apiV1EventDatesGet(page?: number, perPage?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (perPage !== undefined && perPage !== null) {
            queryParameters = queryParameters.set('per_page', <any>perPage);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<EventDateListResponse>(`${this.basePath}/api/v1/event-dates`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get event date
     *
     * @param id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1EventDatesIdGet(id: number, observe?: 'body', reportProgress?: boolean): Observable<EventDate>;
    public apiV1EventDatesIdGet(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EventDate>>;
    public apiV1EventDatesIdGet(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EventDate>>;
    public apiV1EventDatesIdGet(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV1EventDatesIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<EventDate>(`${this.basePath}/api/v1/event-dates/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Search for event dates
     *
     * @param page The page number (1 indexed).
     * @param perPage Items per page
     * @param keyword Looks for keyword in name, description and tags.
     * @param dateFrom Looks for events at or after this date, e.g. 2020-12-31.
     * @param dateTo Looks for events at or before this date, e.g. 2020-12-31.
     * @param coordinate Looks for events around this coordinate. Expects comma separated latitude and longitude, e.g. \&quot;51.9077888,10.4333312\&quot;. See distance.
     * @param distance Looks for events around a coordinate within this distance. Expects distance in meters. See coordinate.
     * @param categoryId Looks for events with this category ids.
     * @param weekday Looks for events at this weekdays (0&#x3D;Sunday, 1&#x3D;Monday, ..).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1EventDatesSearchGet(page?: number, perPage?: number, keyword?: string, dateFrom?: string, dateTo?: string, coordinate?: string, distance?: number, categoryId?: Array<number>, weekday?: Array<number>, observe?: 'body', reportProgress?: boolean): Observable<EventDateSearchResponse>;
    public apiV1EventDatesSearchGet(page?: number, perPage?: number, keyword?: string, dateFrom?: string, dateTo?: string, coordinate?: string, distance?: number, categoryId?: Array<number>, weekday?: Array<number>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EventDateSearchResponse>>;
    public apiV1EventDatesSearchGet(page?: number, perPage?: number, keyword?: string, dateFrom?: string, dateTo?: string, coordinate?: string, distance?: number, categoryId?: Array<number>, weekday?: Array<number>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EventDateSearchResponse>>;
    public apiV1EventDatesSearchGet(page?: number, perPage?: number, keyword?: string, dateFrom?: string, dateTo?: string, coordinate?: string, distance?: number, categoryId?: Array<number>, weekday?: Array<number>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {










        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (perPage !== undefined && perPage !== null) {
            queryParameters = queryParameters.set('per_page', <any>perPage);
        }
        if (keyword !== undefined && keyword !== null) {
            queryParameters = queryParameters.set('keyword', <any>keyword);
        }
        if (dateFrom !== undefined && dateFrom !== null) {
            queryParameters = queryParameters.set('date_from', <any>dateFrom);
        }
        if (dateTo !== undefined && dateTo !== null) {
            queryParameters = queryParameters.set('date_to', <any>dateTo);
        }
        if (coordinate !== undefined && coordinate !== null) {
            queryParameters = queryParameters.set('coordinate', <any>coordinate);
        }
        if (distance !== undefined && distance !== null) {
            queryParameters = queryParameters.set('distance', <any>distance);
        }
        if (categoryId) {
            categoryId.forEach((element) => {
                queryParameters = queryParameters.append('category_id', <any>element);
            })
        }
        if (weekday) {
            weekday.forEach((element) => {
                queryParameters = queryParameters.append('weekday', <any>element);
            })
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<EventDateSearchResponse>(`${this.basePath}/api/v1/event-dates/search`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List dates for event
     *
     * @param id
     * @param page The page number (1 indexed).
     * @param perPage Items per page
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1EventsIdDatesGet(id: number, page?: number, perPage?: number, observe?: 'body', reportProgress?: boolean): Observable<EventDateListResponse>;
    public apiV1EventsIdDatesGet(id: number, page?: number, perPage?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EventDateListResponse>>;
    public apiV1EventsIdDatesGet(id: number, page?: number, perPage?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EventDateListResponse>>;
    public apiV1EventsIdDatesGet(id: number, page?: number, perPage?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV1EventsIdDatesGet.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (perPage !== undefined && perPage !== null) {
            queryParameters = queryParameters.set('per_page', <any>perPage);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<EventDateListResponse>(`${this.basePath}/api/v1/events/${encodeURIComponent(String(id))}/dates`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Search for event dates of organization
     * Includes events that organization is referencing.
     * @param id
     * @param page The page number (1 indexed).
     * @param perPage Items per page
     * @param keyword Looks for keyword in name, description and tags.
     * @param dateFrom Looks for events at or after this date, e.g. 2020-12-31.
     * @param dateTo Looks for events at or before this date, e.g. 2020-12-31.
     * @param coordinate Looks for events around this coordinate. Expects comma separated latitude and longitude, e.g. \&quot;51.9077888,10.4333312\&quot;. See distance.
     * @param distance Looks for events around a coordinate within this distance. Expects distance in meters. See coordinate.
     * @param categoryId Looks for events with this category ids.
     * @param weekday Looks for events at this weekdays (0&#x3D;Sunday, 1&#x3D;Monday, ..).
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1OrganizationsIdEventDatesSearchGet(id: number, page?: number, perPage?: number, keyword?: string, dateFrom?: string, dateTo?: string, coordinate?: string, distance?: number, categoryId?: Array<number>, weekday?: Array<number>, observe?: 'body', reportProgress?: boolean): Observable<EventDateSearchResponse>;
    public apiV1OrganizationsIdEventDatesSearchGet(id: number, page?: number, perPage?: number, keyword?: string, dateFrom?: string, dateTo?: string, coordinate?: string, distance?: number, categoryId?: Array<number>, weekday?: Array<number>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EventDateSearchResponse>>;
    public apiV1OrganizationsIdEventDatesSearchGet(id: number, page?: number, perPage?: number, keyword?: string, dateFrom?: string, dateTo?: string, coordinate?: string, distance?: number, categoryId?: Array<number>, weekday?: Array<number>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EventDateSearchResponse>>;
    public apiV1OrganizationsIdEventDatesSearchGet(id: number, page?: number, perPage?: number, keyword?: string, dateFrom?: string, dateTo?: string, coordinate?: string, distance?: number, categoryId?: Array<number>, weekday?: Array<number>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV1OrganizationsIdEventDatesSearchGet.');
        }










        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (perPage !== undefined && perPage !== null) {
            queryParameters = queryParameters.set('per_page', <any>perPage);
        }
        if (keyword !== undefined && keyword !== null) {
            queryParameters = queryParameters.set('keyword', <any>keyword);
        }
        if (dateFrom !== undefined && dateFrom !== null) {
            queryParameters = queryParameters.set('date_from', <any>dateFrom);
        }
        if (dateTo !== undefined && dateTo !== null) {
            queryParameters = queryParameters.set('date_to', <any>dateTo);
        }
        if (coordinate !== undefined && coordinate !== null) {
            queryParameters = queryParameters.set('coordinate', <any>coordinate);
        }
        if (distance !== undefined && distance !== null) {
            queryParameters = queryParameters.set('distance', <any>distance);
        }
        if (categoryId) {
            categoryId.forEach((element) => {
                queryParameters = queryParameters.append('category_id', <any>element);
            })
        }
        if (weekday) {
            weekday.forEach((element) => {
                queryParameters = queryParameters.append('weekday', <any>element);
            })
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<EventDateSearchResponse>(`${this.basePath}/api/v1/organizations/${encodeURIComponent(String(id))}/event-dates/search`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
