/**
 * Oveda API
 * This API provides endpoints to interact with the Oveda data.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ErrorResponse } from '../model/errorResponse';
import { EventReference } from '../model/eventReference';
import { EventReferenceListResponse } from '../model/eventReferenceListResponse';
import { UnprocessableEntityResponse } from '../model/unprocessableEntityResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class EventReferencesService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get event reference
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1EventReferencesIdGet(id: number, observe?: 'body', reportProgress?: boolean): Observable<EventReference>;
    public apiV1EventReferencesIdGet(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EventReference>>;
    public apiV1EventReferencesIdGet(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EventReference>>;
    public apiV1EventReferencesIdGet(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV1EventReferencesIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<EventReference>(`${this.basePath}/api/v1/event-references/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List incoming event references of organization
     * 
     * @param id 
     * @param page The page number (1 indexed).
     * @param per_page Items per page
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1OrganizationsIdEventReferencesIncomingGet(id: number, page?: number, per_page?: number, observe?: 'body', reportProgress?: boolean): Observable<EventReferenceListResponse>;
    public apiV1OrganizationsIdEventReferencesIncomingGet(id: number, page?: number, per_page?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EventReferenceListResponse>>;
    public apiV1OrganizationsIdEventReferencesIncomingGet(id: number, page?: number, per_page?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EventReferenceListResponse>>;
    public apiV1OrganizationsIdEventReferencesIncomingGet(id: number, page?: number, per_page?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV1OrganizationsIdEventReferencesIncomingGet.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (per_page !== undefined && per_page !== null) {
            queryParameters = queryParameters.set('per_page', <any>per_page);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<EventReferenceListResponse>(`${this.basePath}/api/v1/organizations/${encodeURIComponent(String(id))}/event-references/incoming`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List outgoing event references of organization
     * 
     * @param id 
     * @param page The page number (1 indexed).
     * @param per_page Items per page
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1OrganizationsIdEventReferencesOutgoingGet(id: number, page?: number, per_page?: number, observe?: 'body', reportProgress?: boolean): Observable<EventReferenceListResponse>;
    public apiV1OrganizationsIdEventReferencesOutgoingGet(id: number, page?: number, per_page?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EventReferenceListResponse>>;
    public apiV1OrganizationsIdEventReferencesOutgoingGet(id: number, page?: number, per_page?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EventReferenceListResponse>>;
    public apiV1OrganizationsIdEventReferencesOutgoingGet(id: number, page?: number, per_page?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV1OrganizationsIdEventReferencesOutgoingGet.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (per_page !== undefined && per_page !== null) {
            queryParameters = queryParameters.set('per_page', <any>per_page);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<EventReferenceListResponse>(`${this.basePath}/api/v1/organizations/${encodeURIComponent(String(id))}/event-references/outgoing`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
